version: '3.7'

volumes:
    var:
        driver: local
    mysqldata:

services:
    # nginx
    web:
        build:
            dockerfile: ./docker/nginx/Dockerfile
        volumes:
            - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
    # PHP
    app:
        build:
            dockerfile: ./docker/php/Dockerfile
            target: app
        extra_hosts:
            - host.docker.internal:host-gateway
    # MySQL
    mysql:
        image: mysql:8.0
        volumes:
            - mysqldata:/var/lib/mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
