version: '3.7'

services:
    # nginx
    web:
        build:
            dockerfile: ./docker/nginx/Dockerfile
        volumes:
            - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    # PHP
    app:
        build:
            dockerfile: ./docker/php/Dockerfile
            target: "${BUILD_TARGET:-app}"
        volumes:
            - .:/var/www/html
            - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro #ro -> read only
        environment:
            XDEBUG_MODE: "${XDEBUG_MODE:-off}"
    # MySQL
    mysql:
        ports:
            - "${MYSQL_PORT}:3306"
        restart: unless-stopped

volumes:
    mysqldata: