version: '3.7'

volumes:
    var:
        driver: local
    mysqldata:

services:
    # nginx
    web:
        image: nginx:latest
        volumes:
            - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
    # PHP
    app:
        build:
            dockerfile: ./docker/php/Dockerfile
            target: app_dev
        volumes:
            - .:/var/www/html
            - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro #ro -> read only
        environment:
            MYSQL_HOST: mysql
            MYSQL_PORT: ${MYSQL_PORT}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            REDIS_HOST: cache
            REDIS_PORT: ${REDIS_PORT}
            XDEBUG_MODE: "${XDEBUG_MODE:-off}"
        extra_hosts:
            - host.docker.internal:host-gateway
    # MySQL
    mysql:
        image: mysql:8.0
        volumes:
            - mysqldata:/var/lib/mysql
        ports:
            - "${MYSQL_PORT}:3306"
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
    # redis
    cache:
        image: redis:latest
